REVOKE ALL ON DATABASE api FROM custom_sql_user;
REVOKE ALL ON SCHEMA public FROM custom_sql_user;
GRANT EXECUTE ON PROCEDURE audit.execute_custom_query TO custom_sql_user;
GRANT EXECUTE ON PROCEDURE audit.get_custom_query TO custom_sql_user;
GRANT EXECUTE ON PROCEDURE audit.revoke_custom_query TO custom_sql_user;
GRANT EXECUTE ON PROCEDURE audit.sign_off_custom_query TO custom_sql_user;
GRANT EXECUTE ON PROCEDURE audit.insert_custom_query TO custom_sql_user;
GRANT CONNECT ON DATABASE api TO custom_sql_user;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM custom_sql_user;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM custom_sql_user;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA audit FROM custom_sql_user;
REVOKE ALL ON ALL TABLES IN SCHEMA audit FROM custom_sql_user;
GRANT USAGE ON SCHEMA audit TO custom_sql_user;
ALTER USER custom_sql_user SET search_path TO audit, public;
