<?php
namespace AppBundle\Repository;

/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends DDBaseRepository
{
}
