<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncomePaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomePaymentRepository extends EntityRepository
{
}
