<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitleRepository extends EntityRepository
{
}
