@startuml
digraph name {
 subgraph "cluster_subnet.public" {
         style=filled;
         color=lightgrey;
         label="data.aws_subnet.public";

         "[root] aws_lb.admin"
         "[root] aws_lb.front"
         "[root] aws_lb_listener.admin"
         "[root] aws_lb_listener.front_http"
         "[root] aws_lb_listener.front_https"
     }

subgraph "cluster_subnet.private" {
        style=filled;
        color=lightgrey;
        label="data.aws_subnet.private";
        "[root] aws_ecs_service.admin";
        "[root] aws_ecs_service.api";
        "[root] aws_ecs_service.front";
        "[root] aws_ecs_service.scan";
        "[root] aws_ecs_service.wkhtmltopdf";
        "[root] module.client_unit_test.var.subnet_ids";
        "[root] module.integration_test.var.subnet_ids";
        "[root] module.reset_database.var.subnet_ids";
        "[root] module.restore.var.subnet_ids";
        "[root] module.restore_from_production.var.subnet_ids";
        "[root] module.backup.var.subnet_ids"
    }

  "[root] aws_lb.admin" -> "[root] aws_lb_listener.admin"
  "[root] aws_lb.front" -> "[root] aws_lb_listener.front_http"
  "[root] aws_lb.front" -> "[root] aws_lb_listener.front_https"
  "[root] aws_lb_listener.front_https" -> "[root] aws_ecs_service.front"
  "[root] aws_lb_listener.admin" -> "[root] aws_ecs_service.admin"

}
@enduml
