
@startuml
    !define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist

    !include AWSPuml/AWSCommon.puml
    !include AWSPuml/AWSSimplified.puml

    !include AWSPuml/Compute/all.puml
    !include AWSPuml/Database/all.puml
    !include AWSPuml/DeveloperTools/all.puml
    !include AWSPuml/General/all.puml
    !include AWSPuml/NetworkingAndContentDelivery/all.puml
    !include AWSPuml/Storage/all.puml

    Cloud9(internal,"internal",)
    ECSService(admin_service,"admin",)
    ECSService(api_service,"api",)
    ECSService(front_service,"front",)
    ECSService(pdf_service,"pdf",)
    ECSService(scan_service,"scan",)
    ECSService(backup_task,"backup",)
    ECSService(restore_task,"restore",)
    ECSService(api_unit_test_task,"api_unit_test",)
    ECSService(integration_test_task,"integration_test",)
    ECSService(client_unit_test_task,"client_unit_test",)
    ElastiCacheForRedis(admin_elasticache,"admin",)
    ElastiCacheForRedis(api_elasticache,"api",)
    ElastiCacheForRedis(front_elasticache,"front",)
    ELBApplicationLoadBalancer(admin_lb,"admin",)
    ELBApplicationLoadBalancer(front_lb,"front",)
    InternetAlt1(whitelist, "whitelisted ips",)
    RDSPostgreSQLinstance(rds,"rds",)
    S3Bucket(backup_bucket, "backup",)
    S3Bucket(pa_uploads_bucket, "pa-uploads",)

    whitelist -[#blue]-> admin_lb: HTTPS
    whitelist -[#blue]-> front_lb: HTTPS
    whitelist -[#red]-> front_lb: HTTP

    admin_lb -[#blue]-> admin_service: HTTPS
    front_lb -[#blue]-> front_service: HTTPS

    admin_service -[#blue]-> api_service: HTTPS
    admin_service -[#green]-> admin_elasticache: TCP:6379
    admin_service -[#blue]-> pa_uploads_bucket: HTTPS

    admin_service -[#red]-> pdf_service: HTTP

    api_unit_test_task -[#green]-> api_elasticache: TCP:6379

    integration_test_task -[#blue]-> admin_lb: HTTPS
    integration_test_task -[#blue]-> front_lb: HTTPS

    api_service -[#purple]-> rds: TCP:5432
    api_service -[#green]-> api_elasticache: TCP:6379

    front_service -[#blue]-> api_service #blue: HTTPS
    front_service -[#green]-> front_elasticache: TCP:6379
    front_service -[#red]-> pdf_service: HTTP
    front_service -[#red]-> scan_service: TCP:8443
    front_service -[#blue]-> pa_uploads_bucket: HTTPS

    backup_task -[#purple]up-> rds: TCP:5432
    backup_task -[#blue]up-> backup_bucket: HTTPS

    restore_task -[#purple]up-> rds: TCP:5432
    restore_task -[#blue]up-> backup_bucket: HTTPS

    internal -[#purple]up-> rds: TCP:5432
@enduml
