<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity as EntityDir;
use Doctrine\ORM\EntityRepository;

/**
 * CasRecRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasRecRepository extends EntityRepository
{

}
