<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Finds a single entity by a set of criteria. Unfiltered, softdelete disabled.
     *
     * @param array      $criteria
     * @param array|null $orderBy
     *
     * @return object|null the entity instance or NULL if the entity can not be found
     */
    public function findUnfilteredOneBy(array $criteria, array $orderBy = null)
    {
        $this->_em->getFilters()->disable('softdeleteable');

        $result = $this->findOneBy($criteria, $orderBy);

        $this->_em->getFilters()->enable('softdeleteable');

        return $result;
    }

    /**
     * @param User $user
     */
    public function hardDeleteExistingUser(User $user)
    {
        $existingSoftDeletedUser = $this->findUnfilteredOneBy(['email' => $user->getEmail()]);
        if ($existingSoftDeletedUser != null) {
            // delete soft deleted user a second time to hard delete it
            $this->_em->remove($existingSoftDeletedUser);
            $this->_em->flush($existingSoftDeletedUser);
        }
    }
}
