-- Example SQL generated by the update statement.
-- For use in understanding how the updates work (including the )

UPDATE public.deputy pub1
SET address1 = CASE WHEN NULLIF(pub2.address1, '') IS NULL THEN pub2.address1 ELSE anon.address1 END,
address2 = CASE WHEN NULLIF(pub2.address2, '') IS NULL THEN pub2.address2 ELSE anon.address2 END,
address3 = CASE WHEN NULLIF(pub2.address3, '') IS NULL THEN pub2.address3 ELSE anon.address3 END,
address4 = CASE WHEN NULLIF(pub2.address4, '') IS NULL THEN pub2.address4 ELSE anon.address4 END,
address5 = CASE WHEN NULLIF(pub2.address5, '') IS NULL THEN pub2.address5 ELSE anon.address5 END,
address_country = CASE WHEN NULLIF(pub2.address_country, '') IS NULL THEN pub2.address_country ELSE anon.address_country END,
address_postcode = CASE WHEN NULLIF(pub2.address_postcode, '') IS NULL THEN pub2.address_postcode ELSE anon.address_postcode END,
deputy_uid = CASE WHEN NULLIF(pub2.deputy_uid, '') IS NULL THEN pub2.deputy_uid ELSE anon.deputy_uid END,
email1 = CASE WHEN NULLIF(pub2.email1, '') IS NULL THEN pub2.email1 ELSE anon.email1 END,
email2 = CASE WHEN NULLIF(pub2.email2, '') IS NULL THEN pub2.email2 ELSE anon.email2 END,
email3 = CASE WHEN NULLIF(pub2.email3, '') IS NULL THEN pub2.email3 ELSE anon.email3 END,
firstname = CASE WHEN NULLIF(pub2.firstname, '') IS NULL THEN pub2.firstname ELSE COALESCE(dd_user.firstname, anon.firstname) END,
lastname = CASE WHEN NULLIF(pub2.lastname, '') IS NULL THEN pub2.lastname ELSE COALESCE(dd_user.lastname, anon.lastname) END,
phone_alternative = CASE WHEN NULLIF(pub2.phone_alternative, '') IS NULL THEN pub2.phone_alternative ELSE anon.phone_alternative END,
phone_main = CASE WHEN NULLIF(pub2.phone_main, '') IS NULL THEN pub2.phone_main ELSE anon.phone_main END
FROM public.deputy as pub2
INNER JOIN processing.deputy AS proc ON pub2.id = proc.id
INNER JOIN (SELECT * FROM anon.deputy ORDER BY ppk_id LIMIT 100 OFFSET 0) AS anon ON proc.ppk_id = anon.ppk_id
LEFT JOIN dd_user ON pub2.user_id = dd_user.id
WHERE pub1.id = pub2.id;
