<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Client;
use AppBundle\Entity\Report\Debt as ReportDebt;
use AppBundle\Entity\Report\Fee as ReportFee;
use AppBundle\Entity\Report\MoneyShortCategory as ReportMoneyShortCategory;
use AppBundle\Entity\Report\Report;
use AppBundle\Entity\ReportInterface;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\ParameterBag;

/**
 * ReportRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    /** @var QueryBuilder */
    private $qb;

    const USER_DETERMINANT = 1;
    const ORG_DETERMINANT = 2;

    /**
     * add empty Debts to Report.
     * Called from doctrine listener.
     *
     * @param Report $report
     *
     * @return int changed records
     */
    public function addDebtsToReportIfMissing(Report $report)
    {
        $ret = 0;

        // skips if already added
        if (count($report->getDebts()) > 0) {
            return $ret;
        }

        foreach (ReportDebt::$debtTypeIds as $row) {
            $debt = new ReportDebt($report, $row[0], $row[1], null);
            $this->_em->persist($debt);
            ++$ret;
        }

        return $ret;
    }

    /**
     * @param Report $report
     * @return int|void
     * @throws \Doctrine\ORM\ORMException
     */
    public function addFeesToReportIfMissing(Report $report)
    {
        // do not add if there are no PAs associated to this client
        $isPaF = function ($user) {
            return $user->isPaDeputy();
        };

        if (0 === $report->getClient()->getUsers()->filter($isPaF)->count()) {
            return;
        }

        $ret = 0;

        // skips if already added
        if (count($report->getFees()) > 0) {
            return $ret;
        }

        foreach (ReportFee::$feeTypeIds as $id => $row) {
            $debt = new ReportFee($report, $id, null);
            $this->_em->persist($debt);
            ++$ret;
        }

        return $ret;
    }

    /**
     * Called from doctrine listener.
     *
     * @param Report $report
     *
     * @return int changed records
     */
    public function addMoneyShortCategoriesIfMissing(Report $report)
    {
        $ret = 0;

        if (count($report->getMoneyShortCategories()) > 0) {
            return $ret;
        }

        $cats = ReportMoneyShortCategory::getCategories('in') + ReportMoneyShortCategory::getCategories('out');
        foreach ($cats as $typeId => $options) {
            $debt = new ReportMoneyShortCategory($report, $typeId, false);
            $this->_em->persist($debt);
            ++$ret;
        }

        return $ret;
    }

    /**
     * @param array $caseNumbers
     * @param string $role
     * @return mixed
     */
    public function findAllActiveReportsByCaseNumbersAndRole(array $caseNumbers, $role)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->leftJoin('r.client', 'c')
            ->leftJoin('c.users', 'u')
            ->where('(r.submitted = false OR r.submitted is null) AND r.unSubmitDate IS NULL AND c.caseNumber IN (:caseNumbers) AND u.roleName = :roleName')
            ->setParameter('caseNumbers',$caseNumbers, Connection::PARAM_STR_ARRAY)
            ->setParameter('roleName', $role);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param int $id
     * @param int $determinant
     * @param ParameterBag $query
     * @param string $select
     * @param string|null $status
     * @return array|mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAllByDeterminant($id, $determinant, ParameterBag $query, $select, $status)
    {
        $this->qb = $this->createQueryBuilder('r');
        $this->qb
            ->select(($select === 'count') ? 'COUNT(DISTINCT r)' : 'r,c')
            ->leftJoin('r.client', 'c');

        if ($determinant === self::USER_DETERMINANT) {
            $this->qb->leftJoin('c.users', 'u')->where('u.id = ' . $id);
        } else {
            $this->qb->leftJoin('c.organisation', 'o')->where('o.isActivated = true AND o.id = ' . $id);
        }

        $this->qb
            ->andWhere('c.archivedAt IS NULL')
            ->andWhere('r.submitted = false OR r.submitted is null');

        if ($searchTerm = $query->get('q')) {
            $this->handleSearchTermFilter($searchTerm);
        }

        $endOfToday = new \DateTime('today midnight');

        if ($status === Report::STATUS_READY_TO_SUBMIT) {
            $this->qb->andWhere('r.reportStatusCached = :status AND r.endDate < :endOfToday')
                ->setParameter('status', $status)
                ->setParameter('endOfToday', $endOfToday);
        } else if ($status === Report::STATUS_NOT_FINISHED) {
            $this->qb->andWhere('r.reportStatusCached = :status OR (r.reportStatusCached = :readyToSubmit AND r.endDate >= :endOfToday)')
                ->setParameter('status', $status)
                ->setParameter('readyToSubmit', Report::STATUS_READY_TO_SUBMIT)
                ->setParameter('endOfToday', $endOfToday);
        } else if ($status === Report::STATUS_NOT_STARTED) {
            $this->qb->andWhere('r.reportStatusCached = :status')
                ->setParameter('status', $status);
        }

        if ($select === 'count') {
            return $this->qb->getQuery()->getSingleScalarResult();
        }

        $this->qb
            ->setFirstResult($query->get('offset', 0))
            ->setMaxResults($query->get('limit', 15))
            ->addOrderBy('r.endDate', 'ASC')
            ->addOrderBy('c.caseNumber', 'ASC');

        $result = $this->qb->getQuery()->getArrayResult();

        return count($result) === 0 ? null : $result;
    }

    /**
     * @param string $searchTerm
     */
    private function handleSearchTermFilter($searchTerm): void
    {
        if (Client::isValidCaseNumber($searchTerm)) {
            $this->qb->andWhere('lower(c.caseNumber) = :cn');
            $this->qb->setParameter('cn', strtolower($searchTerm));
        } else {

            $searchTerms = explode(' ', $searchTerm);

            if (count($searchTerms) === 1) {
                $this->addBroadMatchFilter($searchTerm);
            } else {
                $this->addFullNameExactMatchFilter($searchTerms[0], $searchTerms[1]);
            }
        }
    }

    /**
     * @param string $query
     */
    private function addBroadMatchFilter($query): void
    {
        $this->qb->andWhere('lower(c.firstname) LIKE :qLike OR lower(c.lastname) LIKE :qLike ');
        $this->qb->setParameter('qLike', '%' . strtolower($query) . '%');
    }

    /**
     * @param string $firstName
     * @param string $lastname
     */
    private function addFullNameExactMatchFilter(string $firstName, string $lastname): void
    {
        $this->qb->andWhere('(lower(c.firstname) = :firstname AND lower(c.lastname) = :lastname)');
        $this->qb->setParameters(['firstname' => strtolower($firstName), 'lastname' => strtolower($lastname),]);
    }
}
