services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $fixtureParams: "%fixtures%"
            $fixturesEnabled: "%env(bool:FIXTURES_ENABLED)%"

    Tests\OPG\Digideps\Backend\Behat\:
        resource: "../tests/Behat/bootstrap/*"
