parameters:
    fixtures:
        account_password: "%env(FIXTURES_ACCOUNTPASSWORD)%"
        legacy_password_hash: "%env(FIXTURES_LEGACYPASSWORDHASH)%"

    # To avoid undefined variable errors at build time during clear-cache, we can define default values for env vars
    # At runtime Symfony will fetch the actual value from the environment
    env(AUDIT_LOG_GROUP_NAME): "dummy-build-time-value-overridden-at-runtime"

    # set this param to a higher value than session_expire_seconds on the client
    user_provider_timeout_seconds: 3901
    client_permissions:
        admin: [ROLE_AD, ROLE_ADMIN]
        frontend: [ROLE_DEPUTY]

    shared_email_domains:
        - "aol.com"
        - "aol.co.uk"
        - "btconnect.com"
        - "btinternet.com"
        - "gmail.com"
        - "googlemail.com"
        - "hotmail.com"
        - "hotmail.co.uk"
        - "icloud.com"
        - "live.co.uk"
        - "live.com"
        - "mac.com"
        - "me.com"
        - "msn.com"
        - "nhs.net"
        - "ntlworld.com"
        - "outlook.com"
        - "sky.com"
        - "talktalk.net"
        - "yahoo.com"
        - "yahoo.co.uk"
        - "example.com"

services:
    em:
        alias: doctrine.orm.default_entity_manager

    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $fixturesEnabled: "%env(bool:FIXTURES_ENABLED)%"
            $yamlFixtureLocation: "%kernel.project_dir%/src/DataFixtures/"
            $fixtureParams: "%fixtures%"
            $symfonyEnvironment: "%kernel.environment%"
            $projectDir: "%kernel.project_dir%"
            $frontendHost: "%env(JWT_HOST)%"
            $workspace: "%workspace%"
            $sessionPrefix: "%env(SESSION_PREFIX)%"
            Predis\ClientInterface: "@predis"
            $redis: "@predis"

    predis:
        class: Predis\Client
        arguments:
            - "%redis_dsn%"

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            $redis: "@predis"
            $options:
                prefix: "%workspace%_%sessionPrefix%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    OPG\Digideps\Backend\:
        resource: "../src/*"
        exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}"

    OPG\Digideps\Backend\Controller\:
        resource: "../src/Controller/"
        tags: [controller.service_arguments]

    OPG\Digideps\Backend\v2\Controller\:
        resource: "../src/v2/Controller"
        tags: [controller.service_arguments]

    OPG\Digideps\Backend\v2\Registration\Controller\:
        resource: "../src/v2/Registration/Controller"
        tags: [controller.service_arguments]

    monolog.processor.add_request_id:
        class: OPG\Digideps\Backend\Service\RequestIdLoggerProcessor
        arguments: ["@service_container"]
        tags:
            - { name: monolog.processor, method: processRecord }

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [setAnnotationReader, ["@annotation_reader"]]
            - [setAttributeReader, ["@attribute_reader"]]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [setAnnotationReader, ["@annotation_reader"]]
            - [setAttributeReader, ["@attribute_reader"]]

    OPG\Digideps\Backend\DataFixtures\:
        resource: "../src/DataFixtures"
        tags: ["doctrine.fixture.orm"]
        autowire: true

    OPG\Digideps\Backend\Controller\Report\ReportController:
        class: OPG\Digideps\Backend\Controller\Report\ReportController
        arguments:
            $updateHandlers:
                [
                    "@rest_handler.report.deputy_costs_estimate_report_update_handler",
                    "@rest_handler.report.deputy_costs_report_update_handler",
                    "@rest_handler.report.pa_fees_expenses_report_update_handler",
                ]

    OPG\Digideps\Backend\EventListener\RestInputOuputFormatter:
        arguments:
            ["@jms_serializer", "@logger", ["json"], "json", "%kernel.debug%"]
        tags:
            - {
                  name: kernel.event_listener,
                  event: kernel.view,
                  method: onKernelView,
              }
            - {
                  name: kernel.event_listener,
                  event: kernel.exception,
                  method: onKernelException,
              }
            - {
                  name: kernel.event_listener,
                  event: kernel.request,
                  method: onKernelRequest,
              }

    OPG\Digideps\Backend\EventListener\DoctrineListener:
        tags:
            - {
                  name: doctrine.event_listener,
                  event: prePersist,
                  method: prePersist,
              }
            - {
                  name: doctrine.event_listener,
                  event: preUpdate,
                  method: preUpdate,
              }
            - {
                  name: doctrine.event_listener,
                  event: preRemove,
                  method: preRemove,
              }

    OPG\Digideps\Backend\EventListener\FixDefaultSchemaListener:
        class: OPG\Digideps\Backend\EventListener\FixDefaultSchemaListener
        tags:
            - {
                  name: doctrine.event_listener,
                  event: postGenerateSchema,
                  method: postGenerateSchema,
              }

    OPG\Digideps\Backend\Factory\OrganisationFactory:
        class: OPG\Digideps\Backend\Factory\OrganisationFactory
        arguments: ["%shared_email_domains%"]
        public: true

    OPG\Digideps\Backend\Service\RestHandler\OrganisationRestHandler:
        class: OPG\Digideps\Backend\Service\RestHandler\OrganisationRestHandler
        arguments:
            - "@em"
            - "@validator"
            - '@OPG\Digideps\Backend\Repository\OrganisationRepository'
            - '@OPG\Digideps\Backend\Repository\UserRepository'
            - '@OPG\Digideps\Backend\Factory\OrganisationFactory'
            - "%shared_email_domains%"

    OPG\Digideps\Backend\Security\RedisUserProvider:
        arguments:
            [
                "@predis",
                "@logger",
                { "timeout_seconds": "%user_provider_timeout_seconds%" },
                '@OPG\Digideps\Backend\Repository\UserRepository',
            ]

    OPG\Digideps\Backend\Security\OrganisationVoter:
        class: OPG\Digideps\Backend\Security\OrganisationVoter
        arguments: ["@security.helper"]
        tags:
            - { name: security.voter }

    OPG\Digideps\Backend\Security\ClientVoter:
        class: OPG\Digideps\Backend\Security\ClientVoter
        arguments: ["@security.helper"]
        tags:
            - { name: security.voter }

    OPG\Digideps\Backend\Security\UserVoter:
        class: OPG\Digideps\Backend\Security\UserVoter
        tags:
            - { name: security.voter }

    OPG\Digideps\Backend\Service\Client\TokenStorage\RedisStorage:
        arguments:
            $redis: "@predis"

    OPG\Digideps\Backend\Service\DataImporter\CsvToArray: ~

    # Disable autowiring for these helper classes
    OPG\Digideps\Backend\Service\ReportStatusService: ~
    OPG\Digideps\Backend\Service\Stats\StatsQueryParameters: ~

    Aws\S3\S3ClientInterface:
        alias: Aws\S3\S3Client

    Aws\S3\S3Client:
        arguments: ["%s3_client_params%"]

    OPG\Digideps\Backend\Service\File\Storage\S3Storage:
        arguments: ['@Aws\S3\S3Client', "%s3_sirius_bucket%", "@logger"]

    OPG\Digideps\Backend\Service\File\Storage\S3SatisfactionDataStorage:
        parent: OPG\Digideps\Backend\Service\File\Storage\S3Storage
        arguments:
            index_1: "%s3_satisfaction_bucket%"

    Symfony\Component\Security\Core\Role\RoleHierarchyInterface: "@security.role_hierarchy"

    OPG\Digideps\Backend\Repository\PreRegistrationRepository:
        class: OPG\Digideps\Backend\Repository\PreRegistrationRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\ClientRepository:
        class: OPG\Digideps\Backend\Repository\ClientRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\DocumentRepository:
        class: OPG\Digideps\Backend\Repository\DocumentRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\ChecklistRepository:
        class: OPG\Digideps\Backend\Repository\ChecklistRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\CourtOrderRepository:
        class: OPG\Digideps\Backend\Repository\CourtOrderRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\CourtOrderDeputyRepository:
        class: OPG\Digideps\Backend\Repository\CourtOrderDeputyRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\DeputyRepository:
        class: OPG\Digideps\Backend\Repository\DeputyRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\NoteRepository:
        class: OPG\Digideps\Backend\Repository\NoteRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\OrganisationRepository:
        class: OPG\Digideps\Backend\Repository\OrganisationRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\ReportRepository:
        class: OPG\Digideps\Backend\Repository\ReportRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\ReportSubmissionRepository:
        class: OPG\Digideps\Backend\Repository\ReportSubmissionRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\SatisfactionRepository:
        class: OPG\Digideps\Backend\Repository\SatisfactionRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\StagingDeputyshipRepository:
        class: OPG\Digideps\Backend\Repository\StagingDeputyshipRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\UserRepository:
        class: OPG\Digideps\Backend\Repository\UserRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\UserResearchResponseRepository:
        class: OPG\Digideps\Backend\Repository\UserResearchResponseRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\AssetRepository:
        class: OPG\Digideps\Backend\Repository\AssetRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Repository\BankAccountRepository:
        class: OPG\Digideps\Backend\Repository\BankAccountRepository
        tags: ["doctrine.repository_service"]

    OPG\Digideps\Backend\Service\Auth\AuthService:
        arguments:
            $clientPermissions: "%client_permissions%"

    OPG\Digideps\Backend\Service\BruteForce\AttemptsInTimeChecker:
        arguments: ["@predis"]
        calls:
            - [setRedisPrefix, ["ac_ret_code"]]
            # after 5 attempts in the last 10 minutes, return a different return code (activate captcha)
            - [addTrigger, [5, 600]]

    OPG\Digideps\Backend\Service\BruteForce\AttemptsIncrementalWaitingChecker:
        arguments: ["@predis"]
        calls:
            - [setRedisPrefix, ["ac_exception"]]
            # after 10 attempts, freeze for 30 minutes
            - [addFreezingRule, [10, 1800]]
            # after further 10 attempts. freeze for 1h
            - [addFreezingRule, [20, 3600]]
            # after further 10 attempts. freeze for 2h
            - [addFreezingRule, [30, 7200]]

    logstash_formatter:
        class: Monolog\Formatter\LogstashFormatter
        arguments:
            - application.api
            - null
            - null
            - ""
            - "1"
    line_formatter:
        class: Monolog\Formatter\LineFormatter

    opg_json_formatter:
        class: OPG\Digideps\Common\Logger\OpgJsonFormatter

    opg_line_formatter:
        class: OPG\Digideps\Common\Logger\OpgLineFormatter

    rest_handler.report.deputy_costs_estimate_report_update_handler:
        class: OPG\Digideps\Backend\Service\RestHandler\Report\DeputyCostsEstimateReportUpdateHandler
        arguments: ["@em"]

    rest_handler.report.deputy_costs_report_update_handler:
        class: OPG\Digideps\Backend\Service\RestHandler\Report\DeputyCostsReportUpdateHandler
        arguments: ["@em"]

    rest_handler.report.pa_fees_expenses_report_update_handler:
        class: OPG\Digideps\Backend\Service\RestHandler\Report\PaFeesExpensesReportUpdateHandler
        arguments: ["@em"]

    PlainUserAssembler:
        class: OPG\Digideps\Backend\v2\Assembler\UserAssembler

    OPG\Digideps\Backend\v2\Assembler\Report\ReportSummaryAssembler: ~
    OPG\Digideps\Backend\v2\Assembler\Report\ReportAssemblerInterface: '@OPG\Digideps\Backend\v2\Assembler\Report\ReportSummaryAssembler'

    PlainOrganisationAssembler:
        class: OPG\Digideps\Backend\v2\Assembler\OrganisationAssembler

    uuid_normalizer:
        class: GBProd\UuidNormalizer\UuidNormalizer
        tags:
            - { name: serializer.normalizer }

    uuid_denormalizer:
        class: GBProd\UuidNormalizer\UuidDenormalizer
        tags:
            - { name: serializer.denormalizer }

    Aws\Ssm\SsmClient:
        arguments: ["%ssm_client_params%"]

    OPG\Digideps\Backend\Service\ParameterStoreService:
        arguments:
            [
                '@Aws\Ssm\SsmClient',
                "%env(PARAMETER_PREFIX)%",
                "%env(FEATURE_FLAG_PREFIX)%",
            ]

    OPG\Digideps\Backend\Security\HeaderTokenAuthenticator:
        class: OPG\Digideps\Backend\Security\HeaderTokenAuthenticator
        arguments:
            $redis: "@predis"

    Aws\SecretsManager\SecretsManagerClient:
        arguments: ["%secrets_manager_client_params%"]

    OPG\Digideps\Backend\Service\SecretManagerService:
        arguments:
            [
                '@Aws\SecretsManager\SecretsManagerClient',
                "%env(SECRETS_PREFIX)%",
            ]

    Aws\CloudWatchLogs\CloudWatchLogsClient:
        class: Aws\CloudWatchLogs\CloudWatchLogsClient
        arguments: ["%cloudwatch_logs_client_params%"]

    OPG\Digideps\Backend\Service\Audit\AwsAuditLogHandler:
        class: OPG\Digideps\Backend\Service\Audit\AwsAuditLogHandler
        arguments:
            - '@Aws\CloudWatchLogs\CloudWatchLogsClient'
            - "%env(AUDIT_LOG_GROUP_NAME)%"

    OPG\Digideps\Backend\Service\Audit\LocalAuditLogHandler:
        class: OPG\Digideps\Backend\Service\Audit\LocalAuditLogHandler

    app.guzzlehttp_clientinterface:
        class: GuzzleHttp\Client
        arguments:
            $config:
                verify: false
                headers:
                    Content-Type: application/json
                timeout: 20
                allow_redirects: false

    app.response_comparer_cli:
        class: OPG\Digideps\Backend\Service\ResponseComparison\ClientsResponseComparer

    app.response_comparer_co:
        class: OPG\Digideps\Backend\Service\ResponseComparison\CourtOrderResponseComparer

    OPG\Digideps\Backend\Command\ApiComparison:
        arguments:
            $httpClient: "@app.guzzlehttp_clientinterface"
            $redis: "@predis"
            $comparers:
                - "@app.response_comparer_cli"
                - "@app.response_comparer_co"

    OPG\Digideps\Backend\v2\Registration\DeputyshipProcessing\DeputyshipsCSVLoader:
        public: true

    OPG\Digideps\Backend\v2\Registration\DeputyshipProcessing\DeputyshipsCandidatesSelector:
        public: true

    OPG\Digideps\Backend\v2\Registration\DeputyshipProcessing\CourtOrderReportCandidatesFactory:
        public: true

    OPG\Digideps\Backend\Domain\Deputyship\DeputyshipProcessingRawDbAccess:
        arguments:
            $ingestWriterEm: "@doctrine.orm.ingestwriter_entity_manager"
        public: true

    OPG\Digideps\Backend\Domain\Deputyship\DeputyshipCandidatesConverter:
        public: true

    OPG\Digideps\Backend\Service\DeputyCaseService:
        public: true

    OPG\Digideps\Backend\v2\Assembler\ClientAssembler:
        public: true

    OPG\Digideps\Backend\v2\Assembler\DeputyAssembler:
        public: true

    OPG\Digideps\Backend\Domain\CourtOrder\CourtOrderService:
        public: true

    OPG\Digideps\Backend\Service\LayRegistrationService:
        public: true

    OPG\Digideps\Backend\Service\DeputyService:
        public: true

    OPG\Digideps\Backend\Service\UserDeputyService:
        public: true

    preCSVDataFactory:
        class: OPG\Digideps\Backend\Factory\ChainedDataFactory
        public: true
        arguments:
            $name: "preCSVDataFactory"
            $dataFactories:
                - [
                      '@OPG\Digideps\Backend\Factory\MissingDeputyDataFactory',
                      "active",
                  ]

    postCSVDataFactory:
        class: OPG\Digideps\Backend\Factory\ChainedDataFactory
        public: true
        arguments:
            $name: "postCSVDataFactory"
            $dataFactories:
                - [
                      '@OPG\Digideps\Backend\Factory\UpdateCourtOrderReportTypeDataFactory',
                      "active",
                  ]
                - [
                      '@OPG\Digideps\Backend\Factory\UpdateDeputyTypeDataFactory',
                      "active",
                  ]
                - [
                      '@OPG\Digideps\Backend\Factory\ClientIdFixDataFactory',
                      "active",
                  ]
                - [
                      '@OPG\Digideps\Backend\Factory\MissingReport\MissingReportDataFactory',
                      "dry-run-only",
                  ]

    OPG\Digideps\Backend\v2\Registration\DeputyshipProcessing\DeputyshipsCSVIngester:
        public: true
        arguments:
            $preCSVDataFactory: "@preCSVDataFactory"
            $postCSVDataFactory: "@postCSVDataFactory"
