INSERT INTO client (address, address2, address3, address4, address5, country, email, firstname, lastname, phone, postcode) VALUESINSERT INTO client (address, address2, address3, address4, address5, country, email, firstname, lastname, phone, postcode)
VALUES
('Eligendi ut iusto architecto vero nihil.', 'Pariatur numquam facilis et ea quisquam.', 'Quia quod fugiat quaerat enim doloribus.', 'Et est modi unde facilis voluptatibus.', 'Voluptatem officia commodi id nostrum sapiente.', 'Deleniti laboriosam qui voluptates et pariatur.', '', 'Madonna', 'Hayes', '768-532-1104', 'uP51 xS6'),
('Minus quo ratione ut vel est.', 'Debitis dolorem quia asperiores in officiis.', 'Quia laudantium qui quo rerum recusandae.', 'Aliquam rerum voluptate beatae nulla inventore.', 'Odio nobis aut ut quisquam nemo.', 'Eum et eligendi quisquam cupiditate quaerat.', '', 'Fausto', 'Abshire', '491-867-1025', 'MF83 la0'),
('Ex at sunt dolorum soluta et.', 'Nihil maiores odit esse ut corrupti.', 'Labore est magni minus temporibus vitae.', 'Quisquam doloremque voluptatibus odit doloribus tempora.', 'Sunt incidunt earum nihil quisquam dicta.', 'Est tempore omnis itaque possimus at.', '', 'Alexandro', 'Nitzsche', '254-693-7181', 'Ik48 uW3'),
('Dolorem vitae in animi autem maiores.', 'At provident est pariatur veritatis neque.', 'Est iste deserunt fugit qui odit.', 'Consectetur quam alias voluptate assumenda corrupti.', 'Itaque eum odio earum aut fugit.', 'Vel similique non eos animi quidem.', '', 'Shad', 'West', '110-237-8945', 'op95 JP4'),
('Debitis quia labore voluptas quae qui.', 'Fugiat ut nam fugit suscipit non.', 'Est quasi fugiat doloribus exercitationem incidunt.', 'Et assumenda iste porro impedit est.', 'Perferendis distinctio est consequatur mollitia ad.', 'Id quisquam beatae nihil qui fugiat.', '', 'Violet', 'Beer', '967-145-2810', 'YR73 fH5'),
('Tempora animi eos pariatur nihil facere.', 'Ut quibusdam rerum veritatis sit sed.', 'Ex in aperiam vero dolor suscipit.', 'Non odio doloribus voluptatibus dolores odit.', 'Tempore quia ut consequatur rerum id.', 'Quas laboriosam explicabo velit quia eveniet.', '', 'Melany', 'Ritchie', '191-056-3824', 'YH71 ws3'),
('Ducimus nostrum iste quis est sed.', 'Non et quis quasi laboriosam excepturi.', 'Nostrum sunt magnam id qui natus.', 'Iure omnis nisi rerum qui maiores.', 'Numquam occaecati perspiciatis voluptate repellat distinctio.', 'Quis eligendi dolorem porro qui sapiente.', '', 'Genoveva', 'Kunze', '698-510-3271', 'jr25 Lx0'),
('Quibusdam inventore et voluptate fugit qui.', 'Beatae minima rem id cupiditate quis.', 'Possimus excepturi et sed tempore assumenda.', 'Ut quo quidem dolorem magnam sed.', 'Nesciunt quidem officiis rerum velit cumque.', 'Architecto aut ducimus modi atque voluptatem.', '', 'Verona', 'Stamm', '437-106-2851', 'td5 Dw1'),
('Amet natus deleniti enim voluptatem architecto.', 'Illo est nobis possimus a necessitatibus.', 'Ullam molestias numquam est quis impedit.', 'Et et occaecati rerum reiciendis qui.', 'Dolor voluptate necessitatibus dolores deleniti omnis.', 'Et dignissimos similique rerum eos commodi.', '', 'Yaamir', 'Lesch', '631-029-1748', 'Ew23 xf6'),
('Ipsum a et repellat debitis inventore.', 'Delectus est amet illo et dignissimos.', 'Praesentium accusantium sed et quisquam nemo.', 'Et porro dignissimos aspernatur rem quia.', 'Atque iste sit repellendus repudiandae eum.', 'Dolores minima quae incidunt placeat voluptas.', '', 'Brielle', 'Schmidt', '286-931-0175', 'EO45 xd3')
