@startuml
digraph something {
	compound = "true"
	newrank = "true"
	subgraph "root" {
		"[root] aws_eip.nat" [label = "aws_eip.nat", shape = "box"]
		"[root] aws_internet_gateway.igw" [label = "aws_internet_gateway.igw", shape = "box"]
		"[root] aws_nat_gateway.nat" [label = "aws_nat_gateway.nat", shape = "box"]
		"[root] aws_route_table.private" [label = "aws_route_table.private", shape = "box"]
		"[root] aws_route_table.public" [label = "aws_route_table.public", shape = "box"]
		"[root] aws_subnet.private" [label = "aws_subnet.private", shape = "box"]
		"[root] aws_subnet.public" [label = "aws_subnet.public", shape = "box"]

		"[root] aws_nat_gateway.nat" -> "[root] aws_eip.nat"
		"[root] aws_nat_gateway.nat" -> "[root] aws_subnet.public"
		"[root] aws_route_table.private" -> "[root] aws_nat_gateway.nat"
		"[root] aws_route_table.public" -> "[root] aws_internet_gateway.igw"
		"[root] aws_subnet.private" -> "[root] aws_route_table.private"
		"[root] aws_subnet.public" -> "[root] aws_route_table.public"
	}
}

nwdiag {
   internet[shape=cloud]
   internet -- igw

  network {
    address = "AWS public ranges"
    igw [shape=circle]
    ngw[address = "eip"];
    alb
  }
  network public {
    address = "172.16.1.x/24"
    ngw[address = "172.16.1.x"];
    alb;
    local;
  }
  network private {
    address = "172.16.2.x/24"
    local [shape=circle];
    webserver
    rds
  }
}

@enduml
