services:
  data_collector.apiCollectorss:
    class: OPG\Digideps\Frontend\Service\ApiCollector
    arguments: ["@rest_client"]
    tags:
      - {
          name: data_collector,
          template: "@OPG/Digideps/Frontend/Manage/api-collector",
          id: "api-collector",
        }
  data_collector.CssClassCollector:
    class: OPG\Digideps\Frontend\Service\CssClassCollector
    tags:
      - {
          name: data_collector,
          template: "@OPG/Digideps/Frontend/Manage/css-class-collector",
          id: "css-class-collector",
        }
    public: false

  Alphagov\Notifications\Client:
    alias: OPG\Digideps\Frontend\Service\Mailer\NotifyClientMock
