services:
  OPG\Digideps\Frontend\Service\Client\RestClientMock:
    class: OPG\Digideps\Frontend\Service\Client\RestClientMock

  Alphagov\Notifications\Client:
    alias: OPG\Digideps\Frontend\Service\Mailer\NotifyClientMock

  OPG\Digideps\Frontend\Service\Client\RestClientInterface:
    alias: OPG\Digideps\Frontend\Service\Client\RestClientMock

  OPG\Digideps\Frontend\Service\Mailer\MailSender:
    class: OPG\Digideps\Frontend\Service\Mailer\MailSender
    arguments:
      $logger: "@logger"
      $notifyClient: '@OPG\Digideps\Frontend\Service\Mailer\NotifyClientMock'
