services:
  Alphagov\Notifications\Client:
    alias: OPG\Digideps\Frontend\Service\Mailer\NotifyClientMock

  OPG\Digideps\Frontend\Service\Mailer\NotifyClientMock:
    class: OPG\Digideps\Frontend\Service\Mailer\NotifyClientMock
    arguments:
      $config:
        httpClient: '@Http\Adapter\Guzzle7\Client'
        apiKey: "%env(NOTIFY_API_KEY)%"
      $logger: "@logger"
