<?php
namespace AppBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-12 at 11:46:19.
 */
class ContactTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Contact
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new Contact;
    }


    public function testGetFullName()
    {
        $mr = new Title();
        $mr->setTitle('Mr');
        
        $this->object->setTitle($mr);
        $this->object->setFirstname('first name');
        $this->object->setLastname('last');
        
        $this->assertEquals('Mr first name last', $this->object->getFullName());
    }
}
