name: "[AWS] ECR scanning results"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for which to check scanning results"
        required: true
        type: string

permissions:
  id-token: write
  security-events: write

jobs:
  ecr-scan-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.10"
          enable-cache: true

      - name: Install dependencies
        working-directory: scripts/pipeline/ecrscan
        run: uv sync --locked

      - name: configure OIDC AWS credentials for ECR scanning
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.MANAGEMENT_ACCOUNT }}:role/digideps-gh-actions-ecr-scan
          role-session-name: github-actions-ecr-scan
          role-duration-seconds: 1800
          aws-region: eu-west-1

      - name: Check ECR scan results
        env:
          TAG: ${{ inputs.tag }}
        run: python ./scripts/pipeline/ecrscan/ecr_scan_results.py --search digideps --ignore mock-sirius --tag "${TAG}" --print_to_terminal --fail_pipe

      - name: Unset AWS variables
        if: always()
        run: |
          {
            echo "AWS_SECRET_ACCESS_KEY="
            echo "AWS_ACCESS_KEY_ID="
            echo "AWS_SESSION_TOKEN="
          } >> "$GITHUB_ENV"
