name: "[Tests] API Integration Tests"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      selection:
        description: "api tests selection to run"
        required: true
        type: string
      branch_name:
        description: "Name of the branch doing the build"
        required: true
        type: string
jobs:
  api-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: run api integration tests
        env:
          SELECTION: ${{ inputs.selection }}
        id: integration-tests
        run: make api-integration-tests ADDITIONAL_CONFIG="" INTEGRATION_SELECTION=${{ inputs.selection }}

      - name: archive test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: api-integration-tests-${{ inputs.selection }}
          path: api/app/tests/coverage/api-integration-tests-${{ inputs.selection }}.xml
