name: "[Terraform] Validate terraform"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    secrets:
      ssh_private_key:
        required: true
    inputs:
      workspace:
        description: "Terraform workspace"
        required: true
        type: string

jobs:
  lint-terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - folder: "environment"
          - folder: "account"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: terraform_version
        name: get terraform version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@b8868247a908f74fafe1905701391580575a6d35 # v4.3.10
        with:
          terraform_directory: terraform/${{ matrix.folder }}

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.terraform_version.outputs.version }}
          terraform_wrapper: false

      - name: terraform fmt ${{ matrix.folder }} check
        run: terraform fmt -check -recursive
        working-directory: terraform/${{ matrix.folder }}

      - id: deploy-key
        uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@a2907c7c7be94301c965ace76a2cfa407ad6fc88 # v4.6.0
        with:
          deploy_key: ${{ secrets.ssh_private_key }}

      - name: configure OIDC AWS credentials for terraform
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.IDENTITY_ACCOUNT }}:role/oidc-digideps-development
          role-session-name: github-actions-terraform
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: terraform validate ${{ inputs.workspace }}
        env:
          TF_WORKSPACE: default
        run: |
          terraform --version
          terraform init
          echo "$TF_WORKSPACE"
          terraform validate
        working-directory: terraform/${{ matrix.folder }}

      - name: Unset AWS variables
        if: always()
        run: |
          {
            echo "AWS_SECRET_ACCESS_KEY="
            echo "AWS_ACCESS_KEY_ID="
            echo "AWS_SESSION_TOKEN="
          } >> "$GITHUB_ENV"
