name: "[Terraform] Validate terraform"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    secrets:
      ssh_private_key:
        required: true
    inputs:
      workspace:
        description: "Terraform workspace"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  security-events: none
  pull-requests: none

jobs:
  lint-terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - folder: "environment"
          - folder: "account"

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - id: terraform_version
        name: get terraform version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@2186f4ee10b7f2839e0c795dcd01c729e6d1d4c0 # v4.8.1
        with:
          terraform_directory: terraform/${{ matrix.folder }}

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.terraform_version.outputs.version }}
          terraform_wrapper: false

      - name: terraform fmt ${{ matrix.folder }} check
        run: terraform fmt -check -recursive
        working-directory: terraform/${{ matrix.folder }}

      - id: deploy-key
        uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@9e756945a9e2b6ac5dc81473b01f8b38600e6ed6 # v4.8.6
        with:
          deploy_key: ${{ secrets.ssh_private_key }}

      - name: configure OIDC AWS credentials for terraform
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.IDENTITY_ACCOUNT }}:role/oidc-digideps-development
          role-session-name: github-actions-terraform
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: terraform validate ${{ inputs.workspace }}
        env:
          TF_WORKSPACE: default
        run: |
          terraform --version
          terraform init
          echo "$TF_WORKSPACE"
          terraform validate
        working-directory: terraform/${{ matrix.folder }}

      - name: Unset AWS variables
        if: always()
        run: |
          {
            echo "AWS_SECRET_ACCESS_KEY="
            echo "AWS_ACCESS_KEY_ID="
            echo "AWS_SESSION_TOKEN="
          } >> "$GITHUB_ENV"
