name: "[Style] PHP CS"

on:
  workflow_call:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/phpcsstandards/phpcs:4.0.1

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Run PHPCS
        run: |
          phpcs --version
          phpcs --standard=phpcs.xml "**.php"
