name: "[Style] PHP CS"

on:
  workflow_call:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/download/4.0.1/phpcs.phar
          php phpcs.phar --version

      - name: Detect changed PHP files
        run: |
          {
            echo "CHANGED_PHP_FILES<<EOF"
            git diff --diff-filter=d --name-only origin/main... -- '**/*.php'
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Run phpcs
        if: env.CHANGED_PHP_FILES != ''
        run: |
          echo "::add-matcher::.github/phpcs-problem-matcher.json"
          php phpcs.phar --standard=./phpcs.xml --report-xml --report-full $CHANGED_PHP_FILES
