name: "[Tests] Client Unit Tests"

defaults:
  run:
    shell: bash

on:
  workflow_call:

permissions:
  id-token: none
  contents: read
  security-events: none
  pull-requests: none

jobs:
  client-js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - run: make js-lint
      - run: make js-test
