name: "[Tests] Miscellaneous Unit Tests"

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  miscellaneous-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: block ips tests
        id: block-ips-tests
        run: make block-ips-tests

      - name: run unit tests for anonymisation
        id: anonymisation-tests
        run: make anonymisation-tests

      - name: run additional composer package checks on client
        id: package-checks-client
        run: python audit-composer-packages.py client.json
        working-directory: scripts/package-audit

      - name: run additional composer package checks on api
        id: package-checks-api
        run: python audit-composer-packages.py api.json
        working-directory: scripts/package-audit

      - name: run linting on all our Dockerfiles
        id: hadolint
        run: |
          set -e
          find . -type f -name "*Dockerfile*" -exec sh -c '
            for file; do
              echo "Processing $file"
              if ! docker run --rm -i -v ./hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < "$file"; then
                echo "==== Dockerfile Linting Failure. Errors found in $file ===="
                exit 1
              fi
            done
          ' sh {} +
          echo "==== Dockerfile Linting Success. No errors ===="

      - name: phpunit common
        id: phpunit-common
        run: make common-phpunit

      - name: phpstan common
        id: phpstan-common
        run: make common-phpstan
