name: wait for ecs services

on:
  workflow_call:
    secrets:
      ssh_private_key:
        required: true
    inputs:
      workspace:
        description: "Workspace"
        required: true
        type: string
      account_name:
        required: true
        type: string
        description: "Account name for oidc"
      account_id:
        required: false
        default: "${{ vars.DEVELOPMENT_ACCOUNT }}"
        type: string
        description: "Account to get credentials for"
      timeout:
        description: "Timeout in minutes to wait for services"
        required: false
        default: "15"
        type: string
      oidc_timeout:
        description: "OIDC session duration"
        required: false
        default: "3600"
        type: string

jobs:
  wait-for-ecs-services:
    name: wait for ecs services to stabilise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: deploy-key
        uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@3a15a16fcc221821c2869eecd8822c5d62af2984 # v4.7.0
        with:
          deploy_key: ${{ secrets.ssh_private_key }}

      - name: configure OIDC AWS credentials for ecs wait
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: "arn:aws:iam::${{ inputs.account_id }}:role/digideps-gh-actions-run-task"
          role-session-name: github-actions-wait-for-ecs-services
          role-duration-seconds: ${{ inputs.oidc_timeout }}
          aws-region: eu-west-1

      - name: wait for all services to be stable
        env:
          WORKSPACE: ${{ inputs.workspace }}
          TIMEOUT: ${{ inputs.timeout }}
        run: |
          chmod +x scripts/pipeline/wait_until_ready/wait_until_ready.sh
          ./scripts/pipeline/wait_until_ready/wait_until_ready.sh \
            "${WORKSPACE}" \
            "${TIMEOUT}" \
            "admin-${WORKSPACE}" \
            "api-${WORKSPACE}" \
            "front-${WORKSPACE}" \
            "htmltopdf-${WORKSPACE}" \
            "mock-sirius-integration${WORKSPACE}" \
            "scan-ecs2508" \
            "sirius-files-sync-${WORKSPACE}"

      - name: Unset AWS variables
        if: always()
        run: |
          {
            echo "AWS_SECRET_ACCESS_KEY="
            echo "AWS_ACCESS_KEY_ID="
            echo "AWS_SESSION_TOKEN="
          } >> "$GITHUB_ENV"
