name: "[Docker] Build web resources"

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: create nvmrc file
        run: grep "FROM node:" Dockerfile | awk -F' ' '{print $2}' | sed 's/^node:\(.*\)-.*/\1/' > .nvmrc
        working-directory: client/docker/resources
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "client/docker/resources/.nvmrc"
      - name: cache node modules
        id: cache-npm
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        env:
          cache-name: cache-node-modules
        with:
          path: client/resources/public
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '**/webpack.config.js') }}
      - name: SLSA
        uses: ministryofjustice/devsecops-actions/sca/slsa@4cd163be7859cd130800d6719d925318826038ea
        with:
          working-directory: client/resources
      - name: Build assets
        run: |
          # Install NPM dependencies
          npm ci
          npm run lint
          npm audit --production

          # Build assets
          NODE_ENV=production npm run build
        working-directory: client/resources
      - name: archive dist
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: web-distribution
          path: client/resources/public
