name: "[Docker] Build web resources"

defaults:
  run:
    shell: bash

on:
  workflow_call:

permissions: {}

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: cache node modules
        id: cache-npm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        env:
          cache-name: cache-node-modules
        with:
          path: client/resources/public
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '**/webpack.config.js') }}

      - name: Build assets
        run: make build-js

      - name: archive dist
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: web-distribution
          path: client/resources/public
