name: "[Manual] Destroy Specific PR environment"

on:
  workflow_dispatch:
    inputs:
      build_identifier:
        description: "PR environment to destroy"
        required: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  cleanup_workspace:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - id: terraform_version
        name: get terraform version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@9e8b7c2fb29c11e77b12913f74459fa48b11829f # v4.8.2
        with:
          terraform_directory: terraform/environment

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          terraform_version: ${{ steps.terraform_version.outputs.version }}
          terraform_wrapper: false

      - id: deploy-key
        uses: "ministryofjustice/opg-github-actions/actions/github-deploy-key@2ad72748485e27f590599a7e9768b9fc0d5b8e03" # v4.8.7
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

      - name: configure OIDC AWS credentials for terraform
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.IDENTITY_ACCOUNT }}:role/oidc-digideps-development
          role-session-name: github-actions-terraform
          role-duration-seconds: 3600
          aws-region: eu-west-1

      - name: clean up environment
        working-directory: ./terraform/environment
        env:
          WORKSPACE: ${{ inputs.build_identifier }}
          TF_VAR_OPG_DOCKER_TAG: foo
        run: |
          echo "Running script against ${WORKSPACE}"
          ./scripts/destroy_workspace.sh "${WORKSPACE}"

      - name: Unset AWS variables
        if: always()
        run: |
          {
            echo "AWS_SECRET_ACCESS_KEY="
            echo "AWS_ACCESS_KEY_ID="
            echo "AWS_SESSION_TOKEN="
          } >> "$GITHUB_ENV"
