name: "[Scheduled] Weekly Update Checks"

on:
  schedule:
    # 9am on Wednesdays
    - cron: "0 9 * * 3"

permissions:
  contents: write
  pull-requests: write
  id-token: none
  security-events: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  run_weekly_update:
    runs-on: ubuntu-latest
    name: run platform version updates
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: update platform versions
        run: python update_platform_versions.py
        working-directory: scripts/pipeline/update_versions

      - name: Create a signed commit
        uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@0d6fd59fa082417466d12e0e1a5e76da3f1712db # v6.1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update platform versions"
          pr_body: "This PR was created automatically to update platform versions."
